// <auto-generated />
using Clothdotnetcorewebapi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ECommerceClothStore.Migrations
{
    [DbContext(typeof(ClothDbContext))]
    [Migration("20210809112648_Clothes")]
    partial class Clothes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Clothdotnetcorewebapi.Models.Cloth", b =>
                {
                    b.Property<int>("CID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CBrand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CDelieveryType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CPrice")
                        .HasColumnType("int");

                    b.Property<string>("CSize")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CID");

                    b.ToTable("Cloths");
                });
#pragma warning restore 612, 618
        }
    }
}
